/* eslint-disable */
const name = 'Enea';
const middle = "X";
const last = `Xharja`;

const sentence = 'it's so cool!' // Uncaught SyntaxError: Unexpected identifier

const sentence2 = "it's sooo cool!"
const sentence3 = 'it\'s sooo cool!'

/*
Single quotes and double quotes are similar, 
but we have both of them as a way to fix the 'Unexpected identifier' error generated by the apostrophe (') 
which is being considered as a single quote character.

You can fix the 'Uncaught SyntaxError: Unexpected identifier' error in two ways:
  - using the escape key or forward slash ('\')
  - using double quotes
*/ 
