/* eslint-disable */
// * Part 1 - Intro to Strings
const name = 'Enea';
const middle = "X";
const last = `Xharja`;

const sentence = 'it's so cool!' // Uncaught SyntaxError: Unexpected identifier

const sentence2 = "it's sooo cool!"
const sentence3 = 'it\'s sooo cool!'

const sentence4 = "it's sooo \"cool\"!"
const sentence5 = `it's sooo "cool"!`

/*
Single quotes and double quotes are similar, 
but we have both of them as a way to fix the 'Unexpected identifier' error generated by the apostrophe (') 
which is being considered as a single quote character.

You can fix the 'Uncaught SyntaxError: Unexpected identifier' error in two ways:
  - using the escape key or backslash ('\')
  - using double quotes


However, even combining the single and double quotes,
strings can get unreadable.
We can avoid all these issues mentioned above, by simply using backticks (``)

*/ 



// * Part 2 - Strings on multiple lines
const song = "It's

Xmas

Time
";

const song2 = `It's

Xmas

Time
`;

const html = `
  <div>
    <h2>JSX</h2>
  </div>
`



/*
The song variable will generate the following error -> Uncaught SyntaxError: Unexpected identifier

It can be fixed: 
- by adding a backslash at the end of every line
- or simply using backticks (``)

Backticks, indeed, are an ideal solution when you have to use HTML in your JS
*/ 